// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiServicesByServiceIdData, DeleteApiServicesByServiceIdResponses, GetApiAuthMeData, GetApiAuthMeResponses, GetApiServicesData, GetApiServicesResponses, PatchApiServicesByServiceIdData, PatchApiServicesByServiceIdResponses, PostApiAuthLoginData, PostApiAuthLoginResponses, PostApiServicesByServiceIdDeploymentsData, PostApiServicesByServiceIdDeploymentsResponses, PostApiServicesByServiceIdEnvironmentsByLabelStartData, PostApiServicesByServiceIdEnvironmentsByLabelStartResponses, PostApiServicesByServiceIdEnvironmentsByLabelStopData, PostApiServicesByServiceIdEnvironmentsByLabelStopResponses, PostApiServicesByServiceIdSwitchData, PostApiServicesByServiceIdSwitchResponses, PostApiServicesData, PostApiServicesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthLoginData, ThrowOnError>) => (options?.client ?? client).post<PostApiAuthLoginResponses, unknown, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getApiServices = <ThrowOnError extends boolean = false>(options?: Options<GetApiServicesData, ThrowOnError>) => (options?.client ?? client).get<GetApiServicesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/services',
    ...options
});

export const postApiServices = <ThrowOnError extends boolean = false>(options?: Options<PostApiServicesData, ThrowOnError>) => (options?.client ?? client).post<PostApiServicesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/services',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getApiAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiAuthMeData, ThrowOnError>) => (options?.client ?? client).get<GetApiAuthMeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});

export const deleteApiServicesByServiceId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiServicesByServiceIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiServicesByServiceIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/services/{serviceId}',
    ...options
});

export const patchApiServicesByServiceId = <ThrowOnError extends boolean = false>(options: Options<PatchApiServicesByServiceIdData, ThrowOnError>) => (options.client ?? client).patch<PatchApiServicesByServiceIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/services/{serviceId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiServicesByServiceIdDeployments = <ThrowOnError extends boolean = false>(options: Options<PostApiServicesByServiceIdDeploymentsData, ThrowOnError>) => (options.client ?? client).post<PostApiServicesByServiceIdDeploymentsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/services/{serviceId}/deployments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiServicesByServiceIdSwitch = <ThrowOnError extends boolean = false>(options: Options<PostApiServicesByServiceIdSwitchData, ThrowOnError>) => (options.client ?? client).post<PostApiServicesByServiceIdSwitchResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/services/{serviceId}/switch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiServicesByServiceIdEnvironmentsByLabelStart = <ThrowOnError extends boolean = false>(options: Options<PostApiServicesByServiceIdEnvironmentsByLabelStartData, ThrowOnError>) => (options.client ?? client).post<PostApiServicesByServiceIdEnvironmentsByLabelStartResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/services/{serviceId}/environments/{label}/start',
    ...options
});

export const postApiServicesByServiceIdEnvironmentsByLabelStop = <ThrowOnError extends boolean = false>(options: Options<PostApiServicesByServiceIdEnvironmentsByLabelStopData, ThrowOnError>) => (options.client ?? client).post<PostApiServicesByServiceIdEnvironmentsByLabelStopResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/services/{serviceId}/environments/{label}/stop',
    ...options
});
