// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:4201' | (string & {});
};

export type ServiceEnvironment = {
    id: string;
    label: string;
    targetUrl: string;
    dockerImage?: string | null;
    status: 'unknown' | 'healthy' | 'degraded' | 'unhealthy' | 'draining';
    weightPercent: number;
    isActive: boolean;
    lastLatencyMs?: number | null;
    lastCheckAt?: string | null;
    hostPort?: number | null;
    appPort?: number | null;
    containerState?: 'running' | 'stopped' | null;
    containerName?: string | null;
};

export type Deployment = {
    id: string;
    version: string;
    status: string;
    createdAt: string;
    environmentId?: string | null;
    dockerImage?: string | null;
};

export type ServiceActivity = {
    id: string;
    type: string;
    message: string;
    createdAt: string;
    actorId?: string | null;
    actorRole?: 'viewer' | 'operator' | 'admin' | null;
    environmentId?: string | null;
    environmentLabel?: string | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
};

export type Service = {
    id: string;
    name: string;
    description?: string | null;
    repositoryUrl?: string | null;
    healthEndpoint?: string | null;
    environments: Array<ServiceEnvironment>;
    deployments: Array<Deployment>;
    activities: Array<ServiceActivity>;
};

/**
 * List of managed services
 */
export type ServicesResponse = Array<Service>;

/**
 * Payload for registering a new service with slot-a/slot-b environments.
 */
export type CreateServiceRequest = {
    name: string;
    description?: string;
    repositoryUrl?: string;
    healthEndpoint?: string;
    environments: Array<{
        label: string;
        dockerImage: string;
        appPort?: number;
        weightPercent?: number;
    }>;
};

/**
 * Partial update for existing service metadata or environment configuration.
 */
export type UpdateServiceRequest = {
    description?: string;
    repositoryUrl?: string;
    healthEndpoint?: string;
    environments?: Array<{
        label: string;
        dockerImage?: string;
        appPort?: number;
    }>;
};

/**
 * Starts a deployment on a specific environment.
 */
export type DeploymentRequest = {
    environmentLabel: string;
    version: string;
    dockerImage: string;
    metadata?: {
        [key: string]: unknown;
    };
};

/**
 * Switches active traffic to a specific environment.
 */
export type SwitchRequest = {
    toLabel: string;
    reason?: string;
};

/**
 * Credentials for JWT-based sign-in.
 */
export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginResponse = {
    token: string;
    role: 'viewer' | 'operator' | 'admin';
    name: string;
};

export type CurrentUserResponse = {
    id: string;
    email: string;
    name: string;
    role: 'viewer' | 'operator' | 'admin';
};

export type ServiceIdParam = {
    serviceId: string;
};

export type EnvironmentLabelParam = {
    serviceId: string;
    label: string;
};

export type SuccessResponse = {
    success: boolean;
};

export type PostApiAuthLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * Authentication success
     */
    200: LoginResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type GetApiServicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/services';
};

export type GetApiServicesResponses = {
    /**
     * List of registered services
     */
    200: ServicesResponse;
};

export type GetApiServicesResponse = GetApiServicesResponses[keyof GetApiServicesResponses];

export type PostApiServicesData = {
    body?: CreateServiceRequest;
    path?: never;
    query?: never;
    url: '/api/services';
};

export type PostApiServicesResponses = {
    /**
     * Created service
     */
    201: Service;
};

export type PostApiServicesResponse = PostApiServicesResponses[keyof PostApiServicesResponses];

export type GetApiAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetApiAuthMeResponses = {
    /**
     * Current authenticated user
     */
    200: CurrentUserResponse;
};

export type GetApiAuthMeResponse = GetApiAuthMeResponses[keyof GetApiAuthMeResponses];

export type DeleteApiServicesByServiceIdData = {
    body?: never;
    path: {
        serviceId: string;
    };
    query?: never;
    url: '/api/services/{serviceId}';
};

export type DeleteApiServicesByServiceIdResponses = {
    /**
     * Service deleted
     */
    200: SuccessResponse;
};

export type DeleteApiServicesByServiceIdResponse = DeleteApiServicesByServiceIdResponses[keyof DeleteApiServicesByServiceIdResponses];

export type PatchApiServicesByServiceIdData = {
    body?: UpdateServiceRequest;
    path: {
        serviceId: string;
    };
    query?: never;
    url: '/api/services/{serviceId}';
};

export type PatchApiServicesByServiceIdResponses = {
    /**
     * Updated service metadata
     */
    200: Service;
};

export type PatchApiServicesByServiceIdResponse = PatchApiServicesByServiceIdResponses[keyof PatchApiServicesByServiceIdResponses];

export type PostApiServicesByServiceIdDeploymentsData = {
    body?: DeploymentRequest;
    path: {
        serviceId: string;
    };
    query?: never;
    url: '/api/services/{serviceId}/deployments';
};

export type PostApiServicesByServiceIdDeploymentsResponses = {
    /**
     * Deployment accepted
     */
    202: unknown;
};

export type PostApiServicesByServiceIdSwitchData = {
    body?: SwitchRequest;
    path: {
        serviceId: string;
    };
    query?: never;
    url: '/api/services/{serviceId}/switch';
};

export type PostApiServicesByServiceIdSwitchResponses = {
    /**
     * Updated service after switch
     */
    200: Service;
};

export type PostApiServicesByServiceIdSwitchResponse = PostApiServicesByServiceIdSwitchResponses[keyof PostApiServicesByServiceIdSwitchResponses];

export type PostApiServicesByServiceIdEnvironmentsByLabelStartData = {
    body?: never;
    path: {
        serviceId: string;
        label: string;
    };
    query?: never;
    url: '/api/services/{serviceId}/environments/{label}/start';
};

export type PostApiServicesByServiceIdEnvironmentsByLabelStartResponses = {
    /**
     * Service after starting the environment
     */
    200: Service;
};

export type PostApiServicesByServiceIdEnvironmentsByLabelStartResponse = PostApiServicesByServiceIdEnvironmentsByLabelStartResponses[keyof PostApiServicesByServiceIdEnvironmentsByLabelStartResponses];

export type PostApiServicesByServiceIdEnvironmentsByLabelStopData = {
    body?: never;
    path: {
        serviceId: string;
        label: string;
    };
    query?: never;
    url: '/api/services/{serviceId}/environments/{label}/stop';
};

export type PostApiServicesByServiceIdEnvironmentsByLabelStopResponses = {
    /**
     * Service after stopping the environment
     */
    200: Service;
};

export type PostApiServicesByServiceIdEnvironmentsByLabelStopResponse = PostApiServicesByServiceIdEnvironmentsByLabelStopResponses[keyof PostApiServicesByServiceIdEnvironmentsByLabelStopResponses];
